version: '2'

services:
    couchbase:
      build: ops/couchbase/
      ports:
        - 8091:8091
        - 8092:8092
        - 8093:8093
        - 11210:11210
      environment:
        - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
        - COUCHBASE_ADMINISTRATOR_PASSWORD=password
        - COUCHBASE_BUCKET=chat-event
        - COUCHBASE_BUCKET_PASSWORD=notSoSecret

    elasticsearch:
      build: ops/elasticsearch/
      ports:
        - "9200:9200"
        - "9300:9300"
        - "9091:9091"
      depends_on:
        - couchbase

    kibana:
      build: ops/kibana/
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch

    chat-event-store:
      build: .
      ports:
        - 80:80
      environment:
        - COUCHBASE_HOST=couchbase
        - COUCHBASE_BUCKET=chat-event
        - COUCHBASE_BUCKET_PASSWORD=notSoSecret
      depends_on:
        - couchbase
